### ISSUE TITLE
getMailboxes limit?

### ISSUE THREAD

**Issue by jtmoulia** [neilj/jmap#2]
Hi, I've been working on the early bits of an IMAP to JMAP proxy, and have been doing a lot of flipping back and forth between the specs. One rough patch I've come across is the JMAP `getMailboxes` command. The spec says that it `Returns a list of all mailbox objects`, but the IMAP spec warns that accounts could have thousands of mailboxes.

If you do want to address those outliers, should the `getMailboxes` command include some sort of protection?

**Comment by neilj** [comment]
At FastMail we probably have a higher proportion of power users than normal. And even for us, well over 90% of users never create a single custom folder (so they only have about 6 mailboxes). There's a long tail, but even at the outmost limit it's fewer than 1000, which honestly is not that much data (1000 JSON Mailbox objects is still smaller than some HTML messages…).

Adding paging would be needless complexity: 99.9% of the time there would never be more than one page, and the rest of the time the data is still going to be perfectly manageable.
