### ISSUE TITLE
JMap Client?

### ISSUE THREAD

**Issue by matrixise** [neilj/jmap#4]
Hi Neil,

from apart FastMail, do you know an example of a small jmap client in console, or a lib?

thanks.

**Comment by neilj** [comment]
Not at the moment, no. However, I have some time to work on the spec
again now, and we hope to do a IMAP <-> JMAP proxy once the spec is more
complete. At that point, it will be a lot more useful for people to
write client libs, and we may try to contribute a few of our own.

Cheers,

Neil.

**Comment by bra-fsn** [comment]
Hi,

Any progress on this? Also, what architecture do you plan to implement for that proxy?
There are a lot of questions here (connection management, load balancing, failure modes, authentication etc etc) if you want to be generic...

**Comment by neilj** [comment]
Work is now underway on a JMAP proxy. The git repo will be under the https://github.com/jmapio group once it is in a semi-reasonable state. For discussion of this or any other JMAP related issue, please join the Google Group at https://groups.google.com/forum/#!forum/jmap-discuss – we're getting all interested parties on to a single mailing list so we can get JMAP moving forward. Thanks.
