### ISSUE TITLE
Bundles and Snoozing

### ISSUE THREAD

**Issue by getaaron** [neilj/jmap#5]
Google's new Inbox app has two great features: Bundles and Snoozing. I think jmap's lack of support for these features will make it difficult for users to want to migrate over to a jmap-based service.

Whether or not Fastmail supports these, it might be a good idea to start discussing representations of them in jmap, which could simply be ignored by clients that don't support them.

Bundles: The server groups together messages within a mailbox that are similar in some way. Actions typically reserved for messages (move to archive, delete, mark as read) can be applied to an entire bundle at once.

Snoozing: Set a time for a message to return to the top of the inbox. This can either be an incoming message you want to deal with later, or a sent message you want to follow up in a bit if you don't get a reply.

**Comment by e12e** [comment]
I don't see why bundles would need any more infrastructure than threads/labels?

As for snoozing: maybe a label with a timestamp?

(Not affiliated with jmap or fastmail, but that's how I read what's in the spec for now)

**Comment by neilj** [comment]
I think these things are worth discussing (although I agree I'm not sure there's anything we need to do for bundles at the API level). The place to do so is the new JMAP mailing list at https://groups.google.com/forum/#!forum/jmap-discuss – the Mailbox team from Dropbox are already on board and I'm sure they'll have some opinions on snoozing! We hope to have some Gmail people there soon too. If you're interested in helping finalise the JMAP spec, please join in there. Thanks.
